/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Transport;
namespace Evernote.EDAM.NoteStore
{

  #if !NETFX_CORE
  [Serializable]
  #endif
  public partial class RelatedNotesTimestampRange : TBase
  {
    private RelatedNotesFields _field;
    private long _minInclusive;
    private long _maxInclusive;
    private double _scoreBoost;
    private RelatedNotesRequirement _requirement;

    public RelatedNotesFields Field
    {
      get
      {
        return _field;
      }
      set
      {
        __isset.field = true;
        this._field = value;
      }
    }

    public long MinInclusive
    {
      get
      {
        return _minInclusive;
      }
      set
      {
        __isset.minInclusive = true;
        this._minInclusive = value;
      }
    }

    public long MaxInclusive
    {
      get
      {
        return _maxInclusive;
      }
      set
      {
        __isset.maxInclusive = true;
        this._maxInclusive = value;
      }
    }

    public double ScoreBoost
    {
      get
      {
        return _scoreBoost;
      }
      set
      {
        __isset.scoreBoost = true;
        this._scoreBoost = value;
      }
    }

    public RelatedNotesRequirement Requirement
    {
      get
      {
        return _requirement;
      }
      set
      {
        __isset.requirement = true;
        this._requirement = value;
      }
    }


    public Isset __isset;
    #if !NETFX_CORE
    [Serializable]
    #endif
    public struct Isset {
      public bool field;
      public bool minInclusive;
      public bool maxInclusive;
      public bool scoreBoost;
      public bool requirement;
    }

    public RelatedNotesTimestampRange() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32) {
              Field = (RelatedNotesFields)iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I64) {
              MinInclusive = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.I64) {
              MaxInclusive = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.Double) {
              ScoreBoost = iprot.ReadDouble();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 5:
            if (field.Type == TType.I32) {
              Requirement = (RelatedNotesRequirement)iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("RelatedNotesTimestampRange");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.field) {
        field.Name = "field";
        field.Type = TType.I32;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32((int)Field);
        oprot.WriteFieldEnd();
      }
      if (__isset.minInclusive) {
        field.Name = "minInclusive";
        field.Type = TType.I64;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(MinInclusive);
        oprot.WriteFieldEnd();
      }
      if (__isset.maxInclusive) {
        field.Name = "maxInclusive";
        field.Type = TType.I64;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(MaxInclusive);
        oprot.WriteFieldEnd();
      }
      if (__isset.scoreBoost) {
        field.Name = "scoreBoost";
        field.Type = TType.Double;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        oprot.WriteDouble(ScoreBoost);
        oprot.WriteFieldEnd();
      }
      if (__isset.requirement) {
        field.Name = "requirement";
        field.Type = TType.I32;
        field.ID = 5;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32((int)Requirement);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("RelatedNotesTimestampRange(");
      sb.Append("Field: ");
      sb.Append(Field);
      sb.Append(",MinInclusive: ");
      sb.Append(MinInclusive);
      sb.Append(",MaxInclusive: ");
      sb.Append(MaxInclusive);
      sb.Append(",ScoreBoost: ");
      sb.Append(ScoreBoost);
      sb.Append(",Requirement: ");
      sb.Append(Requirement);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
