/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

namespace Evernote.EDAM.NoteStore
{
  public enum RelatedNotesFields
  {
    RNF_CREATED = 1,
    RNF_PLACENAME = 3,
  }
}
