/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

namespace Evernote.EDAM.NoteStore
{
  public enum RelatedNotesRequirement
  {
    RNR_MUST = 1,
    RNR_MUST_NOT = 2,
    RNR_SHOULD = 3,
  }
}
