/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Evernote.EDAM.Type
{
  public enum NoteSortOrder
  {
    CREATED = 1,
    UPDATED = 2,
    RELEVANCE = 3,
    UPDATE_SEQUENCE_NUMBER = 4,
    TITLE = 5,
  }
}
