/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Evernote.EDAM.Type
{
  public enum PrivilegeLevel
  {
    NORMAL = 1,
    PREMIUM = 3,
    MANAGER = 7,
    SUPPORT = 8,
    ADMIN = 9,
  }
}
